### ISSUE TITLE
Errors on install with react 17

### ISSUE THREAD

**Issue by Powersource** [brianmcallister/react-auto-scroll#35]
The peer dependencies for this module is for react `^16.8` so when I have this installed and try to install react 17 it gives me an error. I would guess that this likely just needs an update of that peer dependency declaration.

**Comment by brianmcallister** [comment]
Hey @Powersource, thanks, good catch! Can you take a look at #36? Hopefully that will fix the issue for you. If so, I'll merge and publish a new patch version.

**Comment by Powersource** [comment]
Thanks for the quick fix, but for my case it turned out this dep wasn't working in the first case where we used it (might have been using it wrong) so I've just uninstalled the dep for now.

**Comment by brianmcallister** [comment]
Oh no! If there's a bug in the library I'd be more than happy to investigate. Or if you just a question about how to use this I can try and fill in any missing details and update the documentation to be more clear.

**Comment by Powersource** [comment]
Thanks for the offer but I think we're fine for now. We might be back though
