### ISSUE TITLE
disable scroll on wheel and showOption?

### ISSUE THREAD

**Issue by pelikhan** [brianmcallister/react-auto-scroll#37]
It is possible to have the behavior of disabling the scroll on wheel and reenable it when fully scrolled down, even with showOption = false?

**Comment by brianmcallister** [comment]
Could you provide a bit more detail on the use case, I'm not sure I fully understand how that would work?

The way I'm interpreting this with `showOption` set to `true` would be that when the user unchecks the checkbox, `preventInteraction` would also be set to `true`.

However, I can't picture how this would work with `showOption` set to `false`. If the user was allowed to scroll up, and then interaction was disabled, _and_ there was no checkbox to get back to the bottom, how would the user ever get back to the bottom? Would you then just be "stuck" in one spot forever?

Let me know if I've misunderstood, happy to continue the conversation.
